import React, { useState } from 'react'
import { UNIVERSAL_TOKENS } from '../utils/tokenRegistry.js'

const SF = (name) =>
  `https://api.scryfall.com/cards/named?exact=${encodeURIComponent(name)}&format=image&version=normal`

// Color map for token backgrounds
const TOKBG = {
  'Green':    '#0d1a0d',
  'Red':      '#180d0d',
  'White':    '#1a1a0d',
  'Blue':     '#0d1220',
  'Black':    '#100d18',
  'Colorless':'#161616',
  '':         '#141414',
}

function TokenCard({ token, onAdd, qty }) {
  const [imgErr, setImgErr] = useState(false)
  const bg = TOKBG[token.color] || '#141414'

  return (
    <div style={{ display:'flex', alignItems:'center', gap:10, padding:'8px 10px', borderRadius:7, border:'1px solid #222', background:'#1a1a1a', marginBottom:5 }}>
      {/* TOKEN IMAGE */}
      <div style={{ width:46, height:64, borderRadius:5, overflow:'hidden', flexShrink:0, border:'1px solid #333', background:bg, display:'flex', alignItems:'center', justifyContent:'center', fontSize:20 }}>
        {token.scryfall && !imgErr ? (
          <img
            src={SF(token.scryfall)}
            alt={token.name}
            style={{ width:'100%', height:'100%', objectFit:'cover' }}
            onError={() => setImgErr(true)}
          />
        ) : (
          <span>{token.art || '◈'}</span>
        )}
      </div>

      {/* TOKEN INFO */}
      <div style={{ flex:1, minWidth:0 }}>
        <div style={{ fontSize:12, fontWeight:500, color:'#e0e0e0', whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' }}>
          {token.name} {token.pt && token.pt !== '—' ? `(${token.pt})` : ''}
        </div>
        <div style={{ fontSize:9, color:'#555', marginTop:2, lineHeight:1.4 }}>{token.type}</div>
        {token.sourceCard && (
          <div style={{ fontSize:8, color:'#3a3a3a', marginTop:2 }}>from: {token.sourceCard}</div>
        )}
        {token.notes && (
          <div style={{ fontSize:8, color:'#2a2a4a', marginTop:1, lineHeight:1.3 }}>{token.notes}</div>
        )}
      </div>

      {/* CREATE BUTTONS */}
      <div style={{ display:'flex', flexDirection:'column', gap:4, flexShrink:0 }}>
        <button
          onClick={() => onAdd(token, 1)}
          style={{ padding:'4px 12px', borderRadius:5, border:'1px solid #2a2050', background:'#0d0a1e', color:'#a78bfa', fontSize:11, cursor:'pointer', fontWeight:600, whiteSpace:'nowrap' }}
        >
          +1
        </button>
        <button
          onClick={() => onAdd(token, 3)}
          style={{ padding:'4px 12px', borderRadius:5, border:'1px solid #1a1a1a', background:'#111', color:'#555', fontSize:11, cursor:'pointer', whiteSpace:'nowrap' }}
        >
          +3
        </button>
      </div>
    </div>
  )
}

export default function TokenPanel({ deckTokens, onAdd, onClose }) {
  const [tab, setTab] = useState('deck') // 'deck' | 'all'
  const [search, setSearch] = useState('')

  const ALL_TOKENS = [
    ...deckTokens,
    ...UNIVERSAL_TOKENS.filter(u => !deckTokens.find(d => d.name === u.name)),
  ]

  const displayed = (tab === 'deck' ? deckTokens : ALL_TOKENS)
    .filter(t => !search || t.name.toLowerCase().includes(search.toLowerCase()))

  return (
    <div style={{ display:'flex', flexDirection:'column', height:'100%' }}>

      {/* TABS */}
      <div style={{ display:'flex', borderBottom:'1px solid #222', flexShrink:0 }}>
        <div
          onClick={() => setTab('deck')}
          style={{ flex:1, padding:'8px 0', textAlign:'center', fontSize:11, cursor:'pointer', color:tab==='deck'?'#a78bfa':'#555', borderBottom:tab==='deck'?'2px solid #a78bfa':'2px solid transparent' }}
        >
          Deck Tokens ({deckTokens.length})
        </div>
        <div
          onClick={() => setTab('all')}
          style={{ flex:1, padding:'8px 0', textAlign:'center', fontSize:11, cursor:'pointer', color:tab==='all'?'#a78bfa':'#555', borderBottom:tab==='all'?'2px solid #a78bfa':'2px solid transparent' }}
        >
          All Tokens ({ALL_TOKENS.length})
        </div>
      </div>

      {/* SEARCH */}
      <div style={{ padding:'8px 12px', borderBottom:'1px solid #1a1a1a', flexShrink:0 }}>
        <input
          value={search}
          onChange={e => setSearch(e.target.value)}
          placeholder="Search tokens..."
          style={{ width:'100%', padding:'6px 10px', borderRadius:6, background:'#0d0d0d', border:'1px solid #222', color:'#ccc', fontSize:11, outline:'none', fontFamily:'inherit' }}
        />
      </div>

      {/* DECK TOKENS EXPLAINER */}
      {tab === 'deck' && deckTokens.length > 0 && !search && (
        <div style={{ padding:'6px 12px', background:'#0d0a1e', borderBottom:'1px solid #1a1a2a', flexShrink:0 }}>
          <div style={{ fontSize:9, color:'#4c3a8a', lineHeight:1.5 }}>
            ✦ These tokens are generated by cards in your deck. Click +1 or +3 to add them to your battlefield.
          </div>
        </div>
      )}

      {/* TOKEN LIST */}
      <div style={{ flex:1, overflowY:'auto', padding:'8px 12px' }}>
        {displayed.length === 0 ? (
          <div style={{ textAlign:'center', padding:30, fontSize:12, color:'#222' }}>
            {tab === 'deck' ? 'No token-producing cards found in your deck' : 'No tokens match your search'}
          </div>
        ) : (
          displayed.map((token, i) => (
            <TokenCard
              key={token.name + i}
              token={token}
              onAdd={onAdd}
            />
          ))
        )}
      </div>
    </div>
  )
}
